name: Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    if: "!contains(github.event.head_commit.author.name, 'SAP Mentors & Friends')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: npm install
      - run: npm run build
      - run: |
          git config --global user.name 'Mike Zaschka'
          git config --global user.email 'mikezaschka@users.noreply.github.com'
      # use standard-version for bumping versions in files,
      # and generating changelog
      # and tagging the release properly
      # and auto-incrementing the release number
      - run: npm run release
      # push to self aka main from within gh action with "release-state"
      # doesn't trigger this workflow again
      # b/c of missing personal access token here
      # - run: git push --follow-tags origin main
      # finally publish the npm package
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}